#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Edge-optimized-models
Version  : 1.0
Release  : 2
URL      : https://github.com/intel/Edge-optimized-models/archive/v1.0.tar.gz
Source0  : https://github.com/intel/Edge-optimized-models/archive/v1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: Edge-optimized-models-data = %{version}-%{release}
Requires: Edge-optimized-models-license = %{version}-%{release}

%description
# Edge optimized models
Collection of Deep Learning topologies and models trained and optimized for Intel's Edge platforms.

%package data
Summary: data components for the Edge-optimized-models package.
Group: Data

%description data
data components for the Edge-optimized-models package.


%package license
Summary: license components for the Edge-optimized-models package.
Group: Default

%description license
license components for the Edge-optimized-models package.


%prep
%setup -q -n Edge-optimized-models-1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540599351
make  %{?_smp_mflags} || :

%install
export SOURCE_DATE_EPOCH=1540599351
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Edge-optimized-models
cp 'MobileNet 1-Class detection/LICENSE.txt' %{buildroot}/usr/share/package-licenses/Edge-optimized-models/'MobileNet 1-Class detection_LICENSE.txt'
cp 'MobileNet 5-Class detection/LICENSE.txt' %{buildroot}/usr/share/package-licenses/Edge-optimized-models/'MobileNet 5-Class detection_LICENSE.txt'
cp 'SqueezeNet 5-Class detection/LICENSE.txt' %{buildroot}/usr/share/package-licenses/Edge-optimized-models/'SqueezeNet 5-Class detection_LICENSE.txt'
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/Edge-optimized-models/LICENSE.txt
:
## install_append content
mkdir -p %{buildroot}/usr/share/openvino/models
find . -mindepth 1 -maxdepth 1 -type d | while IFS= read -r model; do
cp -a "$model" %{buildroot}/usr/share/openvino/models/
done
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
"/usr/share/openvino/models/MobileNet 1-Class detection/LICENSE.txt"
"/usr/share/openvino/models/MobileNet 1-Class detection/MobileNetSSD-1class-test.prototxt"
"/usr/share/openvino/models/MobileNet 1-Class detection/MobileNetSSD-1class-train.prototxt"
"/usr/share/openvino/models/MobileNet 1-Class detection/MobileNetSSD-1class.caffemodel"
"/usr/share/openvino/models/MobileNet 1-Class detection/MobileNetSSD-1class.prototxt"
"/usr/share/openvino/models/MobileNet 1-Class detection/README.md"
"/usr/share/openvino/models/MobileNet 5-Class detection/LICENSE.txt"
"/usr/share/openvino/models/MobileNet 5-Class detection/MobileNetSSD-5Class-test.prototxt"
"/usr/share/openvino/models/MobileNet 5-Class detection/MobileNetSSD-5Class-train.prototxt"
"/usr/share/openvino/models/MobileNet 5-Class detection/MobileNetSSD-5Class.caffemodel"
"/usr/share/openvino/models/MobileNet 5-Class detection/MobileNetSSD-5Class.prototxt"
"/usr/share/openvino/models/MobileNet 5-Class detection/README.md"
"/usr/share/openvino/models/SqueezeNet 5-Class detection/LICENSE.txt"
"/usr/share/openvino/models/SqueezeNet 5-Class detection/README.md"
"/usr/share/openvino/models/SqueezeNet 5-Class detection/SqueezeNetSSD-5Class-test.prototxt"
"/usr/share/openvino/models/SqueezeNet 5-Class detection/SqueezeNetSSD-5Class-train.prototxt"
"/usr/share/openvino/models/SqueezeNet 5-Class detection/SqueezeNetSSD-5Class.caffemodel"
"/usr/share/openvino/models/SqueezeNet 5-Class detection/SqueezeNetSSD-5Class.prototxt"

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Edge-optimized-models/LICENSE.txt
"/usr/share/package-licenses/Edge-optimized-models/MobileNet 1-Class detection_LICENSE.txt"
"/usr/share/package-licenses/Edge-optimized-models/MobileNet 5-Class detection_LICENSE.txt"
"/usr/share/package-licenses/Edge-optimized-models/SqueezeNet 5-Class detection_LICENSE.txt"
